#!/usr/bin/env bash

# detect flag
CANARY=false
for arg; do
  [[ $arg == "--canary" ]] && CANARY=true
done

if $CANARY; then
  URL="https://discord.com/api/download/canary?platform=linux&format=tar.gz"
  DEST="DiscordCanary"
  DESKTOP="discord-canary.desktop"
  NAME="Discord Canary"
  WM="discord-canary"
  EXEC="DiscordCanary"
else
  URL="https://discord.com/api/download?platform=linux&format=tar.gz"
  DEST="Discord"
  DESKTOP="discord.desktop"
  NAME="Discord"
  WM="discord"
  EXEC="Discord"
fi

WD=~/disco-updater
mkdir -p "$WD" && cd "$WD"
aria2c -x16 "$URL" -o dl.tar.gz
tar -zxf dl.tar.gz

# copy the extracted folder (named $DEST) into /opt
sudo rm -rf /opt/"$DEST"
sudo cp -r "$DEST" /opt/"$DEST"

# write desktop file
sudo tee /usr/share/applications/"$DESKTOP" > /dev/null <<EOF
[Desktop Entry]
Name=$NAME
StartupWMClass=$WM
Comment=Free voice and text chat
GenericName=Internet Messenger
Exec=/opt/$DEST/$EXEC
Icon=/opt/$DEST/discord.png
Type=Application
Categories=Network;InstantMessaging;
EOF

cd ~ && rm -rf "$WD"
echo "Installed $NAME"
